import { StyleSheet } from "react-native";
import Theme from "../../constants/Theme";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.COLORS.lightGrey,
  },
  viewQuestion: {
    height: 250,
    backgroundColor: Theme.COLORS.main,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  txtQuestion: {
    fontSize: 24,
    fontWeight: "bold",
    color: Theme.COLORS.white,
    textAlign: "center",
    width: Theme.SIZES.width,
    flex: 1,
    textAlignVertical: "center",
    marginBottom: 35,
  },
  viewBottomQues: {
    width: "100%",
    position: "absolute",
    bottom: 0,
    alignSelf: "center",
    flexDirection: "row",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  viewNumberQuestion: {
    backgroundColor: Theme.COLORS.white,
    width: 60,
    height: 35,
    justifyContent: "center",
    alignItems: "center",
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    marginLeft: 2,
    marginBottom: 2,
  },
  txtNumberQuestion: {
    fontSize: 16,
    color: Theme.COLORS.grey,
    fontWeight: "bold",
  },
  viewCoundownTimer: {
    backgroundColor: Theme.COLORS.white,
    borderRadius: 60,
    marginBottom: -30,
    elevation: 10,
  },
  viewAnswer: {
    width: "100%",
    marginTop: 60,
  },
  viewContainBtnAnswer: {
    minHeight: Theme.SIZES.heightItem + 2,
    borderRadius: 6,
    backgroundColor: Theme.COLORS.white,
    alignItems: "center",
    flexDirection: "row",
  },
  viewBtnAnswer: {
    alignItems: "center",
    flexDirection: "row",
  },
  viewLineBtnAnswer: {
    height: "100%",
    width: 1,
    backgroundColor: Theme.COLORS.lightBlue,
  },
  txtAnswer: {
    flex: 1,
    marginHorizontal: 10,
    fontSize: 16,
    fontWeight: "bold",
    color: Theme.COLORS.grey,
  },
  viewContainButtonNext: {
    minWidth: 100,
    borderRadius: 5,
    backgroundColor: Theme.COLORS.main,
    height: Theme.SIZES.heightItem - 8,
    position: "absolute",
    bottom: 15,
    right: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  txtButtonNext: {
    fontSize: 16,
    color: Theme.COLORS.white,
    fontWeight: "bold",
  },
});
